import './globals.css'
import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'

/* const inter = Inter({ subsets: ['latin'] })
body tag className={inter.className} */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>
        {children}
        </main>
      </body>
    </html>
  )
}
